export enum StringValue {
	R = '\n',
	T = '\t',
	T2 = '\t\t',
	T3 = '\t\t\t',
	OPEN = '{',
	CLOSE = '}',
	DTO = 'Dto',
	SPACE = ' ',
	EMPTY = '',
	ENUM = 'Enum',
	NUMBER = 'number',
	STRING = 'string',
	BOOLEAN = 'boolean',
	ARRAY = 'Array<',
	DATE= 'Date',
	TAB= '[]',
	ELSE_EMPTY_ARRAY = ' ?? []',
	COALESCE_NULL = ' ?? null',
	ELSE_NULL = ' : null',
	MAP_VALUE = '?.map(value => ',
	STRING_TO_DATE = 'DateHelper.fromUtcStringToDate(',
	DATE_TO_STRING= 'DateHelper.fromDateToString(',
	DOT = '.',
	COLON = ':',
	SEMI_COLON= ';',
	THIS = 'this',
	VALUE = 'value',
	LOWER_DTO = 'dto',
	IF = ' ? ',
	PUBLIC = 'public',
	FROM_DTO_STRING = 'fromDto',
	TO_DTO_STRING = 'toDto'
}